apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets  # Deployment dosyasında bu ismi vermiştik
  namespace: monitoring  # <--- KRİTİK NOKTA: Bu secret monitoring odasında olacak
type: Opaque
data:
  # Değerler Base64 formatında olmalı!
  # admin -> YWRtaW4=
  admin-user: YWRtaW4=
  admin-password: YWRtaW4=