#Create secrets.yaml and copy this to infrastructure/k8s then fill the values
apiVersion: v1
kind: Secret
metadata:
  name: service-secrets
  namespace: take-my-order
type: Opaque
stringData:
  DB_PASSWORD: "BURAYA_SIFRE_GELECEK"
  DB_USERNAME: "BURAYA_KULLANICI_ADI_GELECEK"
  KEYCLOAK_ADMIN_PASSWORD: "BURAYA_KEYCLOAK_SIFRESI"