/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.berkay.kafka.identity.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RoleEventAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8794452351599870905L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RoleEventAvroModel\",\"namespace\":\"com.berkay.kafka.identity.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"roleId\",\"type\":[\"null\",{\"type\":\"string\",\"logicalType\":\"uuid\"}],\"default\":null},{\"name\":\"name\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"userType\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"organizationalUnitId\",\"type\":[\"null\",{\"type\":\"string\",\"logicalType\":\"uuid\"}],\"default\":null},{\"name\":\"version\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"eventType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"permissions\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"PermissionAvroModel\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"code\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"domain\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"active\",\"type\":[\"null\",\"boolean\"],\"default\":null},{\"name\":\"isRestricted\",\"type\":[\"null\",\"boolean\"],\"default\":null},{\"name\":\"createdAt\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"updatedAt\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
  }

  private static final BinaryMessageEncoder<RoleEventAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RoleEventAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RoleEventAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RoleEventAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RoleEventAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RoleEventAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RoleEventAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RoleEventAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RoleEventAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID id;
  private java.util.UUID roleId;
  private java.lang.String name;
  private java.lang.String userType;
  private java.util.UUID organizationalUnitId;
  private java.lang.Long version;
  private java.lang.String eventType;
  private java.util.List<com.berkay.kafka.identity.avro.model.PermissionAvroModel> permissions;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RoleEventAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param roleId The new value for roleId
   * @param name The new value for name
   * @param userType The new value for userType
   * @param organizationalUnitId The new value for organizationalUnitId
   * @param version The new value for version
   * @param eventType The new value for eventType
   * @param permissions The new value for permissions
   */
  public RoleEventAvroModel(java.util.UUID id, java.util.UUID roleId, java.lang.String name, java.lang.String userType, java.util.UUID organizationalUnitId, java.lang.Long version, java.lang.String eventType, java.util.List<com.berkay.kafka.identity.avro.model.PermissionAvroModel> permissions) {
    this.id = id;
    this.roleId = roleId;
    this.name = name;
    this.userType = userType;
    this.organizationalUnitId = organizationalUnitId;
    this.version = version;
    this.eventType = eventType;
    this.permissions = permissions;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return roleId;
    case 2: return name;
    case 3: return userType;
    case 4: return organizationalUnitId;
    case 5: return version;
    case 6: return eventType;
    case 7: return permissions;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.util.UUID)value$; break;
    case 1: roleId = (java.util.UUID)value$; break;
    case 2: name = value$ != null ? value$.toString() : null; break;
    case 3: userType = value$ != null ? value$.toString() : null; break;
    case 4: organizationalUnitId = (java.util.UUID)value$; break;
    case 5: version = (java.lang.Long)value$; break;
    case 6: eventType = value$ != null ? value$.toString() : null; break;
    case 7: permissions = (java.util.List<com.berkay.kafka.identity.avro.model.PermissionAvroModel>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.util.UUID getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.util.UUID value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'roleId' field.
   * @return The value of the 'roleId' field.
   */
  public java.util.UUID getRoleId() {
    return roleId;
  }


  /**
   * Sets the value of the 'roleId' field.
   * @param value the value to set.
   */
  public void setRoleId(java.util.UUID value) {
    this.roleId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'userType' field.
   * @return The value of the 'userType' field.
   */
  public java.lang.String getUserType() {
    return userType;
  }


  /**
   * Sets the value of the 'userType' field.
   * @param value the value to set.
   */
  public void setUserType(java.lang.String value) {
    this.userType = value;
  }

  /**
   * Gets the value of the 'organizationalUnitId' field.
   * @return The value of the 'organizationalUnitId' field.
   */
  public java.util.UUID getOrganizationalUnitId() {
    return organizationalUnitId;
  }


  /**
   * Sets the value of the 'organizationalUnitId' field.
   * @param value the value to set.
   */
  public void setOrganizationalUnitId(java.util.UUID value) {
    this.organizationalUnitId = value;
  }

  /**
   * Gets the value of the 'version' field.
   * @return The value of the 'version' field.
   */
  public java.lang.Long getVersion() {
    return version;
  }


  /**
   * Sets the value of the 'version' field.
   * @param value the value to set.
   */
  public void setVersion(java.lang.Long value) {
    this.version = value;
  }

  /**
   * Gets the value of the 'eventType' field.
   * @return The value of the 'eventType' field.
   */
  public java.lang.String getEventType() {
    return eventType;
  }


  /**
   * Sets the value of the 'eventType' field.
   * @param value the value to set.
   */
  public void setEventType(java.lang.String value) {
    this.eventType = value;
  }

  /**
   * Gets the value of the 'permissions' field.
   * @return The value of the 'permissions' field.
   */
  public java.util.List<com.berkay.kafka.identity.avro.model.PermissionAvroModel> getPermissions() {
    return permissions;
  }


  /**
   * Sets the value of the 'permissions' field.
   * @param value the value to set.
   */
  public void setPermissions(java.util.List<com.berkay.kafka.identity.avro.model.PermissionAvroModel> value) {
    this.permissions = value;
  }

  /**
   * Creates a new RoleEventAvroModel RecordBuilder.
   * @return A new RoleEventAvroModel RecordBuilder
   */
  public static com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder newBuilder() {
    return new com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder();
  }

  /**
   * Creates a new RoleEventAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RoleEventAvroModel RecordBuilder
   */
  public static com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder newBuilder(com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder other) {
    if (other == null) {
      return new com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder();
    } else {
      return new com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new RoleEventAvroModel RecordBuilder by copying an existing RoleEventAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new RoleEventAvroModel RecordBuilder
   */
  public static com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder newBuilder(com.berkay.kafka.identity.avro.model.RoleEventAvroModel other) {
    if (other == null) {
      return new com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder();
    } else {
      return new com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for RoleEventAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RoleEventAvroModel>
    implements org.apache.avro.data.RecordBuilder<RoleEventAvroModel> {

    private java.util.UUID id;
    private java.util.UUID roleId;
    private java.lang.String name;
    private java.lang.String userType;
    private java.util.UUID organizationalUnitId;
    private java.lang.Long version;
    private java.lang.String eventType;
    private java.util.List<com.berkay.kafka.identity.avro.model.PermissionAvroModel> permissions;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.roleId)) {
        this.roleId = data().deepCopy(fields()[1].schema(), other.roleId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.userType)) {
        this.userType = data().deepCopy(fields()[3].schema(), other.userType);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.organizationalUnitId)) {
        this.organizationalUnitId = data().deepCopy(fields()[4].schema(), other.organizationalUnitId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.version)) {
        this.version = data().deepCopy(fields()[5].schema(), other.version);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.eventType)) {
        this.eventType = data().deepCopy(fields()[6].schema(), other.eventType);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.permissions)) {
        this.permissions = data().deepCopy(fields()[7].schema(), other.permissions);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing RoleEventAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.berkay.kafka.identity.avro.model.RoleEventAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.roleId)) {
        this.roleId = data().deepCopy(fields()[1].schema(), other.roleId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.userType)) {
        this.userType = data().deepCopy(fields()[3].schema(), other.userType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.organizationalUnitId)) {
        this.organizationalUnitId = data().deepCopy(fields()[4].schema(), other.organizationalUnitId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.version)) {
        this.version = data().deepCopy(fields()[5].schema(), other.version);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.eventType)) {
        this.eventType = data().deepCopy(fields()[6].schema(), other.eventType);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.permissions)) {
        this.permissions = data().deepCopy(fields()[7].schema(), other.permissions);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.util.UUID getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder setId(java.util.UUID value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'roleId' field.
      * @return The value.
      */
    public java.util.UUID getRoleId() {
      return roleId;
    }


    /**
      * Sets the value of the 'roleId' field.
      * @param value The value of 'roleId'.
      * @return This builder.
      */
    public com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder setRoleId(java.util.UUID value) {
      validate(fields()[1], value);
      this.roleId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'roleId' field has been set.
      * @return True if the 'roleId' field has been set, false otherwise.
      */
    public boolean hasRoleId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'roleId' field.
      * @return This builder.
      */
    public com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder clearRoleId() {
      roleId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder setName(java.lang.String value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'userType' field.
      * @return The value.
      */
    public java.lang.String getUserType() {
      return userType;
    }


    /**
      * Sets the value of the 'userType' field.
      * @param value The value of 'userType'.
      * @return This builder.
      */
    public com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder setUserType(java.lang.String value) {
      validate(fields()[3], value);
      this.userType = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'userType' field has been set.
      * @return True if the 'userType' field has been set, false otherwise.
      */
    public boolean hasUserType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'userType' field.
      * @return This builder.
      */
    public com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder clearUserType() {
      userType = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'organizationalUnitId' field.
      * @return The value.
      */
    public java.util.UUID getOrganizationalUnitId() {
      return organizationalUnitId;
    }


    /**
      * Sets the value of the 'organizationalUnitId' field.
      * @param value The value of 'organizationalUnitId'.
      * @return This builder.
      */
    public com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder setOrganizationalUnitId(java.util.UUID value) {
      validate(fields()[4], value);
      this.organizationalUnitId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'organizationalUnitId' field has been set.
      * @return True if the 'organizationalUnitId' field has been set, false otherwise.
      */
    public boolean hasOrganizationalUnitId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'organizationalUnitId' field.
      * @return This builder.
      */
    public com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder clearOrganizationalUnitId() {
      organizationalUnitId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'version' field.
      * @return The value.
      */
    public java.lang.Long getVersion() {
      return version;
    }


    /**
      * Sets the value of the 'version' field.
      * @param value The value of 'version'.
      * @return This builder.
      */
    public com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder setVersion(java.lang.Long value) {
      validate(fields()[5], value);
      this.version = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'version' field has been set.
      * @return True if the 'version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'version' field.
      * @return This builder.
      */
    public com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder clearVersion() {
      version = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventType' field.
      * @return The value.
      */
    public java.lang.String getEventType() {
      return eventType;
    }


    /**
      * Sets the value of the 'eventType' field.
      * @param value The value of 'eventType'.
      * @return This builder.
      */
    public com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder setEventType(java.lang.String value) {
      validate(fields()[6], value);
      this.eventType = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'eventType' field has been set.
      * @return True if the 'eventType' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'eventType' field.
      * @return This builder.
      */
    public com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'permissions' field.
      * @return The value.
      */
    public java.util.List<com.berkay.kafka.identity.avro.model.PermissionAvroModel> getPermissions() {
      return permissions;
    }


    /**
      * Sets the value of the 'permissions' field.
      * @param value The value of 'permissions'.
      * @return This builder.
      */
    public com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder setPermissions(java.util.List<com.berkay.kafka.identity.avro.model.PermissionAvroModel> value) {
      validate(fields()[7], value);
      this.permissions = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'permissions' field has been set.
      * @return True if the 'permissions' field has been set, false otherwise.
      */
    public boolean hasPermissions() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'permissions' field.
      * @return This builder.
      */
    public com.berkay.kafka.identity.avro.model.RoleEventAvroModel.Builder clearPermissions() {
      permissions = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RoleEventAvroModel build() {
      try {
        RoleEventAvroModel record = new RoleEventAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.util.UUID) defaultValue(fields()[0]);
        record.roleId = fieldSetFlags()[1] ? this.roleId : (java.util.UUID) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.String) defaultValue(fields()[2]);
        record.userType = fieldSetFlags()[3] ? this.userType : (java.lang.String) defaultValue(fields()[3]);
        record.organizationalUnitId = fieldSetFlags()[4] ? this.organizationalUnitId : (java.util.UUID) defaultValue(fields()[4]);
        record.version = fieldSetFlags()[5] ? this.version : (java.lang.Long) defaultValue(fields()[5]);
        record.eventType = fieldSetFlags()[6] ? this.eventType : (java.lang.String) defaultValue(fields()[6]);
        record.permissions = fieldSetFlags()[7] ? this.permissions : (java.util.List<com.berkay.kafka.identity.avro.model.PermissionAvroModel>) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RoleEventAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<RoleEventAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RoleEventAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<RoleEventAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










