apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service # Deployment İsmi
  namespace: take-my-order
  labels:
    app: customer-service # Deployment Etiketi
spec:
  replicas: 1 # Kaç kopya çalışacak?
  selector:
    matchLabels:
      app: customer-service # Pod Seçicisi
  template:
    metadata:
      labels:
        app: customer-service # Pod Etiketi
    spec:
      nodeSelector:
        node-type: app
      containers:
        - name: customer-service # Konteyner İsmi
          image: berkayozr/customer-service:v1 # Dockerhub'da build ettiğimiz imaj
          imagePullPolicy: Always            # Docker Hub'dan çek
          ports:
            - containerPort: 8184           # Application.yml içindeki customer portu
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "800Mi"
              cpu: "1000m"

          # Self-Healing Spring Boot'un /actuator/health adresi, uygulamanın nabzıdır. Eğer veritabanı bağlantısı koparsa bu adres DOWN döner
          # ve Kubernetes bunu görüp "Bu pod bozulmuş, yeniden başlatayım" der.
          livenessProbe: # Kubernetes, Pod'un içine sürekli "Hey, orada mısın?" diye sorar.
            httpGet:
              path: /actuator/health
              port: 8184
            initialDelaySeconds: 90  # İlk kontrol için 1.5 dakika bekle (ARM yavaşlığı için)
            periodSeconds: 10        # 10 saniyede bir kontrol et
            timeoutSeconds: 5
            failureThreshold: 10     # 10 kere başarısız olursa restart at

          readinessProbe: # Kubernetes, "Trafiği sana yönlendireyim mi, yoksa hala veritabanına bağlanmaya mı çalışıyorsun?" diye sorar.
            httpGet:
              path: /actuator/health
              port: 8184
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10

          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: SPRING_PROFILES_ACTIVE

            - name: CUSTOMER_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: CUSTOMER_SERVICE_PORT

            # --- Veritabanı Ayarları (ConfigMap ve Secret'tan) ---
            - name: MASTER_PRIVATE_IP
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: MASTER_PRIVATE_IP

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: DB_PORT

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: DB_PASSWORD

            # 👇 --- KEYCLOAK AYARLARI ---
            - name: KEYCLOAK_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: KEYCLOAK_SERVER_URL

            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: KEYCLOAK_REALM

            - name: KEYCLOAK_MASTER_REALM
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: KEYCLOAK_MASTER_REALM

            - name: KEYCLOAK_ADMIN_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: KEYCLOAK_ADMIN_CLIENT_ID

            - name: KEYCLOAK_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: KEYCLOAK_ADMIN_USERNAME

            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD


              # --- compression type ---
            - name: KAFKA_PRODUCER_CONFIG_COMPRESSION_TYPE
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: KAFKA_PRODUCER_CONFIG_COMPRESSION_TYPE

            # --- Kafka Ayarları ---
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: KAFKA_BOOTSTRAP_SERVERS

            - name: SCHEMA_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: SCHEMA_REGISTRY_URL

            - name: TRACING_SAMPLING_PROBABILITY
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: TRACING_SAMPLING_PROBABILITY

            - name: ZIPKIN_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: ZIPKIN_URL
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service # Gateway buna bu isimle ulaşacak Servis İsmi
  namespace: take-my-order
spec:
  type: ClusterIP
  selector:
    app: customer-service # Servis Bağlantısı
  ports:
    - name: http
      port: 80
      targetPort: 8184