apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: take-my-order
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      nodeSelector:
        node-type: gateway
      containers:
        - name: gateway-service
          image: berkayozr/gateway-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "600Mi"
              cpu: "800m"

          # Self-Healing Spring Boot'un /actuator/health adresi, uygulamanın nabzıdır. Eğer veritabanı bağlantısı koparsa bu adres DOWN döner
          # ve Kubernetes bunu görüp "Bu pod bozulmuş, yeniden başlatayım" der.
          livenessProbe: # Kubernetes, Pod'un içine sürekli "Hey, orada mısın?" diye sorar.
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90  # İlk kontrol için 1.5 dakika bekle (ARM yavaşlığı için)
            periodSeconds: 10        # 10 saniyede bir kontrol et
            timeoutSeconds: 5
            failureThreshold: 10     # 10 kere başarısız olursa restart at

          readinessProbe: # Kubernetes, "Trafiği sana yönlendireyim mi, yoksa hala veritabanına bağlanmaya mı çalışıyorsun?" diye sorar.
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10

          env:

            - name: ORDER_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: ORDER_SERVICE_URI

            - name: IDENTITY_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: IDENTITY_SERVICE_URI

            - name: PAYMENT_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: PAYMENT_SERVICE_URI

            - name: RESTAURANT_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: RESTAURANT_SERVICE_URI

            - name: GATEWAY_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: GATEWAY_SERVICE_PORT

            - name: KEYCLOAK_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: KEYCLOAK_SERVER_URL # http://keycloak-service:8080 veya IP

            - name: KEYCLOAK_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: KEYCLOAK_ISSUER_URI

            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: KEYCLOAK_REALM

            - name: TRACING_SAMPLING_PROBABILITY
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: TRACING_SAMPLING_PROBABILITY

            - name: ZIPKIN_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: ZIPKIN_URL

            # --- Diğer Ayarlar ---
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: LOG_LEVEL

            - name: SHOW_SQL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: SHOW_SQL
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: take-my-order
spec:
  type: ClusterIP # Ingress arkasında olduğu için ClusterIP
  selector:
    app: gateway-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
