apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: take-my-order
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      nodeSelector:
        node-type: app
      containers:
        - name: payment-service
          image: berkayozr/payment-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8182
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "800Mi"
              cpu: "1000m"

          # Self-Healing Spring Boot'un /actuator/health adresi, uygulamanın nabzıdır. Eğer veritabanı bağlantısı koparsa bu adres DOWN döner
          # ve Kubernetes bunu görüp "Bu pod bozulmuş, yeniden başlatayım" der.
          livenessProbe: # Kubernetes, Pod'un içine sürekli "Hey, orada mısın?" diye sorar.
            httpGet:
              path: /actuator/health
              port: 8182
            initialDelaySeconds: 90  # İlk kontrol için 1.5 dakika bekle (ARM yavaşlığı için)
            periodSeconds: 10        # 10 saniyede bir kontrol et
            timeoutSeconds: 5
            failureThreshold: 10     # 10 kere başarısız olursa restart at

          readinessProbe: # Kubernetes, "Trafiği sana yönlendireyim mi, yoksa hala veritabanına bağlanmaya mı çalışıyorsun?" diye sorar.
            httpGet:
              path: /actuator/health
              port: 8182
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10

          env:

            - name: PAYMENT_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: PAYMENT_SERVICE_PORT

            - name: MASTER_PRIVATE_IP
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: MASTER_PRIVATE_IP

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: DB_PORT

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: DB_PASSWORD

            # --- Kafka ---
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: KAFKA_BOOTSTRAP_SERVERS

            - name: SCHEMA_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: SCHEMA_REGISTRY_URL

            - name: TRACING_SAMPLING_PROBABILITY
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: TRACING_SAMPLING_PROBABILITY

            # --- compression type ---
            - name: KAFKA_PRODUCER_CONFIG_COMPRESSION_TYPE
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: KAFKA_PRODUCER_CONFIG_COMPRESSION_TYPE

            - name: ZIPKIN_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: ZIPKIN_URL

            # --- Diğer Ayarlar ---
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: LOG_LEVEL

            - name: SHOW_SQL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: SHOW_SQL
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: take-my-order
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - name: http
      port: 80
      targetPort: 8182