<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.berkay</groupId>
        <artifactId>identity-service</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>identity-container</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.8.5</version>
        </dependency>
        <dependency>
            <groupId>com.berkay</groupId>
            <artifactId>identity-domain-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.berkay</groupId>
            <artifactId>identity-application-service</artifactId>
        </dependency>
        <dependency>
            <groupId>com.berkay</groupId>
            <artifactId>identity-application</artifactId>
        </dependency>
        <dependency>
            <groupId>com.berkay</groupId>
            <artifactId>identity-dataaccess</artifactId>
        </dependency>
        <dependency>
            <groupId>com.berkay</groupId>
            <artifactId>identity-messaging</artifactId>
        </dependency>
        <dependency>
            <groupId>com.berkay</groupId>
            <artifactId>identity-infrastructure</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
        </dependency>
        <dependency>
            <groupId>io.zipkin.reporter2</groupId>
            <artifactId>zipkin-reporter-brave</artifactId>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-database-postgresql</artifactId>
        </dependency>


        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <image>
                        <name>${project.groupId}/identity.service:${project.version}</name>
                    </image>
                    <mainClass>com.berkay.identity.service.domain.IdentityServiceApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <phase>install</phase>
                        <goals>
                            <goal>build-image</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>