/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.berkay.kafka.order.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RestaurantInformationAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3899319355289286767L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RestaurantInformationAvroModel\",\"namespace\":\"com.berkay.kafka.order.avro.model\",\"fields\":[{\"name\":\"restaurantId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"merchantId\",\"type\":[\"null\",{\"type\":\"string\",\"logicalType\":\"uuid\"}],\"default\":null},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"active\",\"type\":\"boolean\"},{\"name\":\"products\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"RestaurantProduct\",\"fields\":[{\"name\":\"productId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"price\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":10,\"scale\":2}},{\"name\":\"available\",\"type\":\"boolean\"}]}}},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"eventType\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<RestaurantInformationAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RestaurantInformationAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RestaurantInformationAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RestaurantInformationAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RestaurantInformationAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RestaurantInformationAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RestaurantInformationAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RestaurantInformationAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RestaurantInformationAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID restaurantId;
  private java.util.UUID merchantId;
  private java.lang.String name;
  private boolean active;
  private java.util.List<com.berkay.kafka.order.avro.model.RestaurantProduct> products;
  private java.time.Instant createdAt;
  private java.lang.String eventType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RestaurantInformationAvroModel() {}

  /**
   * All-args constructor.
   * @param restaurantId The new value for restaurantId
   * @param merchantId The new value for merchantId
   * @param name The new value for name
   * @param active The new value for active
   * @param products The new value for products
   * @param createdAt The new value for createdAt
   * @param eventType The new value for eventType
   */
  public RestaurantInformationAvroModel(java.util.UUID restaurantId, java.util.UUID merchantId, java.lang.String name, java.lang.Boolean active, java.util.List<com.berkay.kafka.order.avro.model.RestaurantProduct> products, java.time.Instant createdAt, java.lang.String eventType) {
    this.restaurantId = restaurantId;
    this.merchantId = merchantId;
    this.name = name;
    this.active = active;
    this.products = products;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.eventType = eventType;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return restaurantId;
    case 1: return merchantId;
    case 2: return name;
    case 3: return active;
    case 4: return products;
    case 5: return createdAt;
    case 6: return eventType;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: restaurantId = (java.util.UUID)value$; break;
    case 1: merchantId = (java.util.UUID)value$; break;
    case 2: name = value$ != null ? value$.toString() : null; break;
    case 3: active = (java.lang.Boolean)value$; break;
    case 4: products = (java.util.List<com.berkay.kafka.order.avro.model.RestaurantProduct>)value$; break;
    case 5: createdAt = (java.time.Instant)value$; break;
    case 6: eventType = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'restaurantId' field.
   * @return The value of the 'restaurantId' field.
   */
  public java.util.UUID getRestaurantId() {
    return restaurantId;
  }


  /**
   * Sets the value of the 'restaurantId' field.
   * @param value the value to set.
   */
  public void setRestaurantId(java.util.UUID value) {
    this.restaurantId = value;
  }

  /**
   * Gets the value of the 'merchantId' field.
   * @return The value of the 'merchantId' field.
   */
  public java.util.UUID getMerchantId() {
    return merchantId;
  }


  /**
   * Sets the value of the 'merchantId' field.
   * @param value the value to set.
   */
  public void setMerchantId(java.util.UUID value) {
    this.merchantId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'active' field.
   * @return The value of the 'active' field.
   */
  public boolean getActive() {
    return active;
  }


  /**
   * Sets the value of the 'active' field.
   * @param value the value to set.
   */
  public void setActive(boolean value) {
    this.active = value;
  }

  /**
   * Gets the value of the 'products' field.
   * @return The value of the 'products' field.
   */
  public java.util.List<com.berkay.kafka.order.avro.model.RestaurantProduct> getProducts() {
    return products;
  }


  /**
   * Sets the value of the 'products' field.
   * @param value the value to set.
   */
  public void setProducts(java.util.List<com.berkay.kafka.order.avro.model.RestaurantProduct> value) {
    this.products = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'eventType' field.
   * @return The value of the 'eventType' field.
   */
  public java.lang.String getEventType() {
    return eventType;
  }


  /**
   * Sets the value of the 'eventType' field.
   * @param value the value to set.
   */
  public void setEventType(java.lang.String value) {
    this.eventType = value;
  }

  /**
   * Creates a new RestaurantInformationAvroModel RecordBuilder.
   * @return A new RestaurantInformationAvroModel RecordBuilder
   */
  public static com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder newBuilder() {
    return new com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder();
  }

  /**
   * Creates a new RestaurantInformationAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RestaurantInformationAvroModel RecordBuilder
   */
  public static com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder newBuilder(com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder other) {
    if (other == null) {
      return new com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder();
    } else {
      return new com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new RestaurantInformationAvroModel RecordBuilder by copying an existing RestaurantInformationAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new RestaurantInformationAvroModel RecordBuilder
   */
  public static com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder newBuilder(com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel other) {
    if (other == null) {
      return new com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder();
    } else {
      return new com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for RestaurantInformationAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RestaurantInformationAvroModel>
    implements org.apache.avro.data.RecordBuilder<RestaurantInformationAvroModel> {

    private java.util.UUID restaurantId;
    private java.util.UUID merchantId;
    private java.lang.String name;
    private boolean active;
    private java.util.List<com.berkay.kafka.order.avro.model.RestaurantProduct> products;
    private java.time.Instant createdAt;
    private java.lang.String eventType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.restaurantId)) {
        this.restaurantId = data().deepCopy(fields()[0].schema(), other.restaurantId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.merchantId)) {
        this.merchantId = data().deepCopy(fields()[1].schema(), other.merchantId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.active)) {
        this.active = data().deepCopy(fields()[3].schema(), other.active);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.products)) {
        this.products = data().deepCopy(fields()[4].schema(), other.products);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.eventType)) {
        this.eventType = data().deepCopy(fields()[6].schema(), other.eventType);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing RestaurantInformationAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.restaurantId)) {
        this.restaurantId = data().deepCopy(fields()[0].schema(), other.restaurantId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.merchantId)) {
        this.merchantId = data().deepCopy(fields()[1].schema(), other.merchantId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.active)) {
        this.active = data().deepCopy(fields()[3].schema(), other.active);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.products)) {
        this.products = data().deepCopy(fields()[4].schema(), other.products);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.eventType)) {
        this.eventType = data().deepCopy(fields()[6].schema(), other.eventType);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'restaurantId' field.
      * @return The value.
      */
    public java.util.UUID getRestaurantId() {
      return restaurantId;
    }


    /**
      * Sets the value of the 'restaurantId' field.
      * @param value The value of 'restaurantId'.
      * @return This builder.
      */
    public com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder setRestaurantId(java.util.UUID value) {
      validate(fields()[0], value);
      this.restaurantId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'restaurantId' field has been set.
      * @return True if the 'restaurantId' field has been set, false otherwise.
      */
    public boolean hasRestaurantId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'restaurantId' field.
      * @return This builder.
      */
    public com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder clearRestaurantId() {
      restaurantId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'merchantId' field.
      * @return The value.
      */
    public java.util.UUID getMerchantId() {
      return merchantId;
    }


    /**
      * Sets the value of the 'merchantId' field.
      * @param value The value of 'merchantId'.
      * @return This builder.
      */
    public com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder setMerchantId(java.util.UUID value) {
      validate(fields()[1], value);
      this.merchantId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'merchantId' field has been set.
      * @return True if the 'merchantId' field has been set, false otherwise.
      */
    public boolean hasMerchantId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'merchantId' field.
      * @return This builder.
      */
    public com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder clearMerchantId() {
      merchantId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder setName(java.lang.String value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'active' field.
      * @return The value.
      */
    public boolean getActive() {
      return active;
    }


    /**
      * Sets the value of the 'active' field.
      * @param value The value of 'active'.
      * @return This builder.
      */
    public com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder setActive(boolean value) {
      validate(fields()[3], value);
      this.active = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'active' field has been set.
      * @return True if the 'active' field has been set, false otherwise.
      */
    public boolean hasActive() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'active' field.
      * @return This builder.
      */
    public com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder clearActive() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'products' field.
      * @return The value.
      */
    public java.util.List<com.berkay.kafka.order.avro.model.RestaurantProduct> getProducts() {
      return products;
    }


    /**
      * Sets the value of the 'products' field.
      * @param value The value of 'products'.
      * @return This builder.
      */
    public com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder setProducts(java.util.List<com.berkay.kafka.order.avro.model.RestaurantProduct> value) {
      validate(fields()[4], value);
      this.products = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'products' field has been set.
      * @return True if the 'products' field has been set, false otherwise.
      */
    public boolean hasProducts() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'products' field.
      * @return This builder.
      */
    public com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder clearProducts() {
      products = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[5], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder clearCreatedAt() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventType' field.
      * @return The value.
      */
    public java.lang.String getEventType() {
      return eventType;
    }


    /**
      * Sets the value of the 'eventType' field.
      * @param value The value of 'eventType'.
      * @return This builder.
      */
    public com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder setEventType(java.lang.String value) {
      validate(fields()[6], value);
      this.eventType = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'eventType' field has been set.
      * @return True if the 'eventType' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'eventType' field.
      * @return This builder.
      */
    public com.berkay.kafka.order.avro.model.RestaurantInformationAvroModel.Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RestaurantInformationAvroModel build() {
      try {
        RestaurantInformationAvroModel record = new RestaurantInformationAvroModel();
        record.restaurantId = fieldSetFlags()[0] ? this.restaurantId : (java.util.UUID) defaultValue(fields()[0]);
        record.merchantId = fieldSetFlags()[1] ? this.merchantId : (java.util.UUID) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.String) defaultValue(fields()[2]);
        record.active = fieldSetFlags()[3] ? this.active : (java.lang.Boolean) defaultValue(fields()[3]);
        record.products = fieldSetFlags()[4] ? this.products : (java.util.List<com.berkay.kafka.order.avro.model.RestaurantProduct>) defaultValue(fields()[4]);
        record.createdAt = fieldSetFlags()[5] ? this.createdAt : (java.time.Instant) defaultValue(fields()[5]);
        record.eventType = fieldSetFlags()[6] ? this.eventType : (java.lang.String) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RestaurantInformationAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<RestaurantInformationAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RestaurantInformationAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<RestaurantInformationAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










