{
  "namespace": "com.berkay.kafka.order.avro.model",
  "type": "record",
  "name": "RestaurantInformationAvroModel",
  "fields": [
    {
      "name": "restaurantId",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "merchantId",
      "type": [
        "null",
        {
          "type": "string",
          "logicalType": "uuid"
        }
      ],
      "default": null
    },
    {
      "name": "name",
      "type": "string"
    },
    {
      "name": "active",
      "type": "boolean"
    },
    {
      "name": "products",
      "type": {
        "type": "array",
        "items": {
          "type": "record",
          "name": "RestaurantProduct",
          "fields": [
            {
              "name": "productId",
              "type": {
                "type": "string",
                "logicalType": "uuid"
              }
            },
            {
              "name": "name",
              "type": "string"
            },
            {
              "name": "price",
              "type": {
                "type": "bytes",
                "logicalType": "decimal",
                "precision": 10,
                "scale": 2
              }
            },
            {
              "name": "available",
              "type": "boolean"
            },
            {
              "name": "hidden",
              "type": "boolean",
              "default": false
            }
          ]
        }
      }
    },
    {
      "name": "available",
      "type": "boolean",
      "default": true
    },
    {
      "name": "createdAt",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "eventType",
      "type": ["null", "string"],
      "default": null
    },
    {
      "name": "minimumOrderAmount",
      "type": [
        "null",
        {
          "type": "bytes",
          "logicalType": "decimal",
          "precision": 10,
          "scale": 2
        }
      ],
      "default": null
    },
    {
      "name": "deliveryFee",
      "type": [
        "null",
        {
          "type": "bytes",
          "logicalType": "decimal",
          "precision": 10,
          "scale": 2
        }
      ],
      "default": null
    }
  ]
}