apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: take-my-order
data:
  DB_NAME: "takemyorder"
  SCHEMA_REGISTRY_DEBUG: "true"
  LOG_LEVEL: "DEBUG"
  SHOW_SQL: "true"
  KEYCLOAK_ISSUER_URI: "http://host.docker.internal:30080"
  SWAGGER_ENABLED: "true"