apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: take-my-order
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: berkayozr/gateway-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "800Mi"
              cpu: "1000m"
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: KEYCLOAK_SERVER_URL
              value: "http://keycloak-service:8080"
            - name: KEYCLOAK_REALM
              value: "take-my-order"
            # Spring Security Ayarları (Token Doğrulama için)
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://keycloak-service:8080/realms/take-my-order"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: "http://keycloak-service:8080/realms/take-my-order/protocol/openid-connect/certs"
          # Ayarları dışarıdan al! Böylece docker-compose ile ayağa kaldırmadaki kısımları bypass et ama bozma
          volumeMounts:
            - name: gateway-config-volume
              # İmajın içindeki config dosyasının YOLUNU hedef aldık
              mountPath: /app/config/application.yml
              subPath: application.yml
      # ConfigMap'i disk gibi tak
      volumes:
        - name: gateway-config-volume
          configMap:
            name: gateway-yml-config # Oluşturduğumuz ConfigMap'i kullan
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: take-my-order
spec:
  type: ClusterIP
  selector:
    app: gateway-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
