apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: take-my-order
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: berkay/payment-service:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8182
          env:
            - name: SERVER_PORT
              value: "8182"
            # Değişkenleri önce tanımlıyoruz (Sıralama Önemli!)
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: DB_PORT
            # Şimdi kullanıyoruz
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://$(DB_HOST):$(DB_PORT)/postgres?currentSchema=payment&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: DB_PASSWORD
            # --- Kafka ---
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: SCHEMA_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: SCHEMA_REGISTRY_URL
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: take-my-order
spec:
  selector:
    app: payment
  ports:
    - name: http
      port: 80
      targetPort: 8182