apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: take-my-order
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.1
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: take-my-order
spec:
  selector:
    app: keycloak
  type: NodePort # Tarayıcıdan erişmek için
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080 # localhost:30080 adresinden gireceğiz