apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: take-my-order
data:
  DB_NAME: "takemyorder"
  SCHEMA_REGISTRY_DEBUG: "false"
  LOG_LEVEL: "INFO" # Prod'da sadece önemli loglar
  SHOW_SQL: "false" # Prod logları şişmesin sadece Localde queryleri görelim