apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: take-my-order
data:
  MASTER_PRIVATE_IP: "private-ip"

  # Veritabanı Ayarları
  DB_NAME: "postgres"
  DB_PORT: "5432"

  # Kafka Ayarları
  KAFKA_BOOTSTRAP_SERVERS: "kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092"
  SCHEMA_REGISTRY_URL: "http://schema-registry-service:8081" # Schema registry kurmadık ama ayarı dursun

  # Keycloak Ayarları
  KEYCLOAK_SERVER_URL: "http://keycloak-service:8080"
  KEYCLOAK_REALM: "take-my-order"
  KEYCLOAK_MASTER_REALM: "master"
  KEYCLOAK_ADMIN_CLIENT_ID: "admin-cli"

  # Servis İsimleri (Java içindeki Feign Client'lar vs için gerekebilir)
  GATEWAY_SERVICE_URI: "http://gateway-service:8080"

  # GATEWAY YÖNLENDİRMELERİ (K8s İÇİN)
  # Burada Service İsimlerini ve Port 80'i (ClusterIP) kullanıyoruz
  ORDER_SERVICE_URI: "http://order-service:80"
  CUSTOMER_SERVICE_URI: "http://customer-service:80"
  PAYMENT_SERVICE_URI: "http://payment-service:80"
  RESTAURANT_SERVICE_URI: "http://restaurant-service:80"

  ZIPKIN_URL: "http://zipkin.monitoring.svc.cluster.local:9411/api/v2/spans"

  # Service Ports
  CUSTOMER_SERVICE_PORT: "8184"
  GATEWAY_SERVICE_PORT: "8080"
  ORDER_SERVICE_PORT: "8181"
  PAYMENT_SERVICE_PORT: "8182"
  RESTAURANT_SERVICE_PORT: "8183"

  #Active Profile Seçimi, değişkenin adı mutlaka SPRING_PROFILES_ACTIVE olmalı. Spring bu env değişkenini kullanacak
  SPRING_PROFILES_ACTIVE: "prod"

  #Other Configs
  TRACING_SAMPLING_PROBABILITY: "0.1"
