server:
  port: ${CUSTOMER_SERVICE_PORT:8184}

logging:
  level:
    com.berkay: ${LOG_LEVEL:DEBUG}

customer-service:
  customer-topic-name: customer
  outbox-scheduler-fixed-rate: 10000 # 10 saniyede bir çalış
  outbox-scheduler-initial-delay: 10000 # Başladıktan 10 sn sonra ilk işi yap

spring:
  jpa:
    open-in-view: false
    show-sql: ${SHOW_SQL:true}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${MASTER_PRIVATE_IP:localhost}:${DB_PORT:5432}/takemyorder?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    schemas: customer
    locations: classpath:db/migration

kafka-config:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:31091,localhost:31092,localhost:31093}
  schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:30081}
  schema-registry-url-key: schema.registry.url
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: ${KAFKA_PRODUCER_CONFIG_COMPRESSION_TYPE:none}
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:30080}
  realm: ${KEYCLOAK_REALM:take-my-order}
  master-realm: ${KEYCLOAK_MASTER_REALM:master}
  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME:admin}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # Prometheus'u dışarı açıyoruz
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name} # Grafana'da hangi servis olduğunu anlamak için
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:30094/api/v2/spans}
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0} # %100 oranında tüm istekleri izle (Production'da bu değer 0.1 yapılır)