customer-service:
  customer-topic-name: customer
  outbox-scheduler-fixed-rate: 10000 # 10 saniyede bir çalış
  outbox-scheduler-initial-delay: 10000 # Başladıktan 10 sn sonra ilk işi yap

spring:
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    schemas: customer
    locations: classpath:db/migration

kafka-config:
  schema-registry-url-key: schema.registry.url
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # Prometheus'u dışarı açıyoruz
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name} # Grafana'da hangi servis olduğunu anlamak için