# 1. Yetkilendirme (Prometheus'un Podları okuyabilmesi için)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: monitoring
---
# 2. Konfigürasyon (Neleri dinleyecek?)
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s # Her 15 saniyede bir veri topla
    scrape_configs:
      # Kubernetes'in kendi metriklerini topla
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: default;kubernetes;https

      # Bizim Java Servisleri (Spring Boot Actuator)
      - job_name: 'spring-actuator'
        metrics_path: '/actuator/prometheus' # Spring Boot'un metrics adresi
        scrape_interval: 5s
        static_configs:
          # Servis İsimleri ve Portları (Hepsi Port 80'de)
          - targets: ['gateway-service.take-my-order.svc.cluster.local:80']
          - targets: ['customer-service.take-my-order.svc.cluster.local:80']
          - targets: ['order-service.take-my-order.svc.cluster.local:80']
          - targets: ['payment-service.take-my-order.svc.cluster.local:80']
          - targets: ['restaurant-service.take-my-order.svc.cluster.local:80']
---
# 3. Deployment (Uygulamanın Kendisi)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      nodeSelector:
        node-type: infra
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: prom/prometheus:v2.45.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          resources:
            requests:
              memory: "512Mi" # Prometheus açken çalışmaz
              cpu: "500m"
            limits:
              memory: "1536Mi" # 1.5 GB'a kadar yolu var, izleme verisi şişebilir
              cpu: "1000m"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-storage-volume
          emptyDir: {}
---
# 4. Servis (Erişim)
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  selector:
    app: prometheus-server
  type: ClusterIP # User girişi bulunmadığından dışarıya kapatılması önerilir. Dışarıya açmak istendiği durumda NodePort ile değiştir ancak zaten Grafana burayı monitor ediyor.
  ports:
    - port: 9090
      targetPort: 9090