apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      nodeSelector:
        node-type: infra
      containers:
        - name: zipkin
          image: openzipkin/zipkin
          ports:
            - containerPort: 9411
          env:
            - name: JAVA_OPTS
              value: "-Xmx256m -Xms256m"
          resources:
            requests:
              memory: "128Mi"
              cpu: "25m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: monitoring
spec:
  type: ClusterIP # User girişi bulunmadığından dışarıya kapatılması önerilir. Dışarıya açmak istendiği durumda NodePort ile değiştir ancak zaten Grafana burayı monitor ediyor.
  selector:
    app: zipkin
  ports:
    - port: 9411
      targetPort: 9411